/**
 * `codewaifu` on the PATH, written by the app itself.
 *
 * A dmg install drops CodeWaifu.app in /Applications and nothing else: no
 * launcher, no shell command. So the shortest path to the bench -
 * `codewaifu pro ssh box`, `codewaifu pro term` - existed on Linux (install.sh
 * writes it) and on an npm install (`bin` in package.json), but not on the
 * platform most people install from. A control surface you cannot reach
 * without remembering an absolute path into a .app bundle is not a control
 * surface, so the app repairs its own launcher at every start.
 *
 * Rules, each of which is a way this could go wrong:
 *
 * - Only darwin. On Linux the installer owns this file and its copy carries the
 *   `.no-sandbox` marker probe that Chromium needs before any of our code runs;
 *   rewriting it from here would quietly drop that. Windows gets a `.cmd` from
 *   install.ps1. Both are skipped, not overwritten.
 * - Only a file we recognise as ours (the marker comment). Anything else at
 *   that path - a symlink from `npm i -g`, an operator's own wrapper - is left
 *   alone and reported, because clobbering it would break a thing we did not
 *   make and cannot restore.
 * - Idempotent. Byte-identical content means no write at all, so a launch does
 *   not churn mtime or fight a filesystem watcher; only a real move (the app
 *   was reinstalled somewhere else) rewrites it.
 * - Atomic. Write a sibling temp file, then rename, so a crash mid-write
 *   cannot leave a truncated launcher on PATH.
 *
 * Every path in here is a *POSIX* path, because the only artifact this module
 * produces is a `/bin/sh` script in `~/.local/bin` on a mac. So it uses
 * `path.posix` and a literal `':'` rather than the host's `path.join` and
 * `path.delimiter`: those are the same thing on darwin and a different thing
 * everywhere else, and a Windows CI runner is a place these contracts have to
 * hold too, since the tests that pin them run there. (`proDiscovery` learned
 * this the hard way - splitting a POSIX `PATH` on `;` turns `C:\...\bin` into
 * nonsense.)
 */
import fs from 'node:fs'
import path from 'node:path'

/** The line that marks a launcher as ours. Checked before any overwrite. */
export const LAUNCHER_MARKER = '# Generated by CodeWaifu'

/**
 * The `PATH` separator this module reads. Deliberately not `path.delimiter`:
 * the launcher only ever exists on darwin, where the separator is `:`, and a
 * host-dependent constant would make the answer depend on the machine asking.
 */
export const PATH_DELIMITER = ':'

export type LauncherOutcome =
  | { action: 'written'; path: string }
  | { action: 'current'; path: string }
  | { action: 'skipped-platform'; platform: string }
  | { action: 'skipped-dev' }
  | { action: 'skipped-no-binary' }
  | { action: 'skipped-foreign'; path: string }
  | { action: 'failed'; path: string; error: string }

export interface LauncherRequest {
  /** `app.isPackaged`. A dev run must not write a launcher at the packaged app. */
  packaged: boolean
  platform: NodeJS.Platform
  /** `process.execPath` when packaged; null when there is nothing to point at. */
  appBinary: string | null
  home: string
  /** Defaults to `~/.local/bin`, the directory herdr and install.sh also use. */
  binDir?: string
}

/**
 * Quote a path for a double-quoted shell string. App bundles live under
 * /Applications in practice, but a user directory can hold a space, a `$` or a
 * quote, and an unescaped one turns the launcher into a syntax error that only
 * shows up when somebody types `codewaifu`.
 */
export function shellEscape(value: string): string {
  return value.replace(/["\\$`]/g, '\\$&')
}

/** The launcher body. Same routing as bin/codewaifu.mjs, in nine lines of sh. */
export function launcherScript(appBinary: string): string {
  const target = shellEscape(appBinary)
  return [
    '#!/bin/sh',
    `${LAUNCHER_MARKER}; rewritten when the app starts. Do not edit by hand.`,
    `APP="${target}"`,
    '[ -x "$APP" ] || { echo "codewaifu: $APP is gone; reinstall CodeWaifu" >&2; exit 1; }',
    '# No arguments starts the companion; a bare subcommand goes to --cli; an',
    '# explicit --flag is passed through untouched (that is how `pro` works too).',
    'if [ "$#" -eq 0 ]; then exec "$APP"; fi',
    'case "$1" in',
    '  --*|-*) exec "$APP" "$@" ;;',
    '  *)      exec "$APP" --cli "$@" ;;',
    'esac',
    ''
  ].join('\n')
}

/** Where the launcher goes. Split out so a caller can show it in a message. */
export function launcherPath(home: string, binDir?: string): string {
  return path.posix.join(binDir ?? path.posix.join(home, '.local', 'bin'), 'codewaifu')
}

/**
 * Is an existing file one we wrote? The marker has to be in the first two
 * lines - it is line 2 of ours - so a foreign script that merely mentions the
 * phrase further down is not claimed and overwritten. And never a symlink:
 * following one would rewrite a file somewhere else entirely.
 */
export function isOurs(stats: fs.Stats, content: string): boolean {
  if (stats.isSymbolicLink()) return false
  const head = content.split('\n', 2).join('\n')
  return head.includes(LAUNCHER_MARKER)
}

/**
 * Make sure `codewaifu` on PATH points at this app. Never throws: a failed
 * launcher write is a convenience lost, not a reason to stop booting.
 */
export function ensureCliLauncher(request: LauncherRequest): LauncherOutcome {
  if (!request.packaged) return { action: 'skipped-dev' }
  if (request.platform !== 'darwin') {
    return { action: 'skipped-platform', platform: request.platform }
  }
  if (!request.appBinary) return { action: 'skipped-no-binary' }

  const target = launcherPath(request.home, request.binDir)
  const wanted = launcherScript(request.appBinary)
  try {
    let stats: fs.Stats | null = null
    try {
      // lstat, so a symlink is seen as a symlink rather than followed into
      // somebody else's file.
      stats = fs.lstatSync(target)
    } catch {
      stats = null
    }

    if (stats) {
      const existing = stats.isFile() ? fs.readFileSync(target, 'utf8') : ''
      if (existing === wanted) return { action: 'current', path: target }
      if (!isOurs(stats, existing)) return { action: 'skipped-foreign', path: target }
    } else {
      fs.mkdirSync(path.posix.dirname(target), { recursive: true, mode: 0o755 })
    }

    const tmp = `${target}.${process.pid}.tmp`
    fs.writeFileSync(tmp, wanted, { mode: 0o755 })
    fs.chmodSync(tmp, 0o755)
    fs.renameSync(tmp, target)
    return { action: 'written', path: target }
  } catch (error) {
    return { action: 'failed', path: target, error: String(error) }
  }
}

/**
 * Is the launcher's directory reachable as a command? Only used to decide
 * whether to warn: a launcher nobody's shell can see is a launcher that reads
 * as "the feature does not exist".
 */
export function binDirOnPath(target: string, envPath: string | undefined): boolean {
  const dirs = (envPath ?? '').split(PATH_DELIMITER).filter(Boolean)
  const dir = path.posix.dirname(target)
  return dirs.some((entry) => entry === dir || entry === `${dir}/`)
}

/** The one line an operator pastes into a shell rc to make the launcher visible. */
export function pathHint(target: string): string {
  return `export PATH="${path.posix.dirname(target)}:$PATH"`
}
